### ISSUE TITLE
ERROR!! Your sidebar section Public API has 0 pages

### ISSUE THREAD

**Issue by FilipeChagasDev** [erez-o/doxiz#57]
DocsForge doesn't work with my repository. The build log doesn't say what the problem is, and I don't know what's wrong with my repository.

The repository: [https://github.com/FilipeChagasDev/FGL](https://github.com/FilipeChagasDev/FGL)

Build log:
```
[0s] ====== BEGIN ====== BUILDING VERSION DOCS ======
[0s] version_name: main, repo: https://github.com/FilipeChagasDev/FGL, initiated by: <a href="https://docsforge.com/profile/filipec/">Filipe Chagas</a>
[0s] task_id: 07e11445-ca54-4a70-afa0-49cfc6d80c12, added to queue on 2021-10-27 17:22:24, waited in queue for 0.06057 seconds. Built with docsforge version 3.4.24
[0s] Using the 'Default' configuration file.
[0s] Cloning git, stage 1/6
[0s] Cloning git : git clone --depth 1 --branch main https://github.com/FilipeChagasDev/FGL .
[0s] Git clone output: Cloning into '.'...
[0s] Finished cloning, Response: 0 - OK
[0s] Creating API pages, stage 2/6.
[0s] Running autodoc of section 'Public API'.
[0s] Running Doxygen with cfg https://fgl.docsforge.com/admin/doxygen-cfg/main/0/
[0s] Creating Tree
[0s] Creating raw API tree
[0s] Deleted 1 Pages with no types.
[0s] Creating raw API Man Pages
[0s] Finished creating raw API pages - found 0 API pages, 0 total API items
[0s] Version contains no API pages. Read the help section (https://help.docsforge.com/latest/customizing-the-public-api/) on how to configure the automatic code documentation.
[0s] Runing markdown on API pages
[0s] Creating user defined groups
[0s] No user defined groups were found
[0s] API pages were created in autodoc section 'Public API'.
[0s] Autolinks created for API pages in section 'Public API'.
[0s] Finished creating Man Pages - created 0 API pages in section 'Public API'
[0s] Creating Non API pages, stage 3/6.
[0s] Yaml configuration file - no file extension, assuming a txt file, displaying as raw output. It is advisasble to explicitly change file name extension so no assumptions will be needed. See "section":"Basic Tutorial", "pageName":"License", "filePath":"LICENSE".
[0s] Changing relative links in doc pages:
[0s] - No relative links needed changing
[0s] Autolinking doc pages:
[0s] API pages referenced in docs:
[0s] - No API pages were referenced in docs
[0s] Autolinking source browser pages:
[0s] Starred 0 api pages.
[0s] Printing API pages, stage 4/6.
[0s] Created 0 API pages in section Public API. 0 API pages do not have code comments. API documentation coverage is 0.0%. See https://fgl.docsforge.com/admin/view-undocumented-pages-log/main/.
[0s] Printing Doc pages, stage 5/6.
[0s] Printed 2 Doc pages
[0s] Wrapping up, stage 6/6.
[0s] Saving YAML configuration file
[0s] Your sidebar section Basic Tutorial has 2 pages.
[0s] ERROR!! Your sidebar section Public API has 0 pages. See https://help.docsforge.com/latest/frequently-asked-questions/ for common solutions.
[0s] Created page paths dictionary
[1s] Created search dictionary
[1s] Created next prev list
[1s] Created sidebar data
[1s] Replaced old docs with new docs.
[1s] Creating sitemap
[1s] ======  END  ====== 

[1s] BUILD STATUS : SUCCESS WITH ERRORS
[1s] Build time: 1.048148 seconds

[1s] Updated github stargazers and forks. Rate limit: 4993
[1s] Cleaning up
```

Configuration file:
```
sidebar:
  Basic Tutorial:
  - Getting Started: README.md
  - License: LICENSE


autodocSettings:
  Public API:
    language: cpp
    INPUT: lib
    EXCLUDE: test tests examples
    EXCLUDE_PATTERNS: '*/tests/* */test/*'
    includeApi: []
    excludeApi: []
    documentSingleUnderscore: true
    documentStatic: true
    documentProtected: true
    extractNonDocComments: false
    extract_namespace_comments: true
    sort_by_type: true
    sort_alphabetically: true
    separate_defines: false
    star_mentioned: true
    star_list: []
    ENABLE_PREPROCESSING: 'YES'
    MACRO_EXPANSION: 'NO'
    EXPAND_ONLY_PREDEF: 'NO'
    PREDEFINED: ''
    SEARCH_INCLUDES: 'YES'
    INCLUDE_PATH: lib
    INCLUDE_FILE_PATTERNS: ''
    ALIASES: ''
    EXAMPLE_PATH: ''
```
